selected_level = 0
selected_world = 0
active = 0
alarm[0] = 30
world_array[0] = "TOWER REALM"
world_array[1] = "COSMIC WEST"
world_array[2] = "NO VACATION CRUISE"
world_array[3] = "21ST CENTURY EMPIRE"
world_array[4] = "TERROR NATION"
world_array[5] = "THE TOP"
world_array[6] = "WORLD EXTRAS"
level_array[0][0] = ["ENTRANCE", entrance_1]
level_array[0][1] = ["MEDIEVAL", medieval_1]
level_array[0][2] = ["RUIN", ruin_1]
level_array[0][3] = ["DUNGEON", dungeon_1]
level_array[1][0] = ["OREGANO DESERT", desert_1]
level_array[1][1] = ["THE WASTEYARD", graveyard_1]
level_array[1][2] = ["FUN FARM", farm_2]
level_array[1][3] = ["SPACE", space_1]
level_array[2][0] = ["BEACH", beach_1]
level_array[2][1] = ["FOREST", forest_1]
level_array[2][2] = ["PINBALL", pinball_1]
level_array[2][3] = ["GOLF", minigolf_1]
level_array[3][0] = ["STREET", street_intro]
level_array[3][1] = ["SEWERS", sewer_1]
level_array[3][2] = ["FACTORY", factory_1]
level_array[3][3] = ["FREEZER", freezer_1]
level_array[4][0] = ["PIZZASCARE", chateau_1]
level_array[4][1] = ["MANSION", mansion_weird2]
level_array[4][2] = ["KIDS PARTY", kidsparty_1]
level_array[4][3] = ["WAR", war_1]
level_array[5][0] = ["TOP", top_1]
level_array[6][0] = ["DRAGON LAIR", dragonlair_1]
level_array[6][1] = ["CITY", city_1]
level_array[6][2] = ["STRONGCOLD", strongcold_10]
stickpressed = 0
key_up2 = 0
key_down2 = 0
key_left2 = 0
key_right2 = 0
key_jump2 = 0
